//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfCompressor.Properties {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PdfCompressor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddPdfFirst {
            get {
                return ResourceManager.GetString("AddPdfFirst", resourceCulture);
            }
        }
        
        internal static string AlreadyEmpty {
            get {
                return ResourceManager.GetString("AlreadyEmpty", resourceCulture);
            }
        }
        
        internal static string ButtonCompress {
            get {
                return ResourceManager.GetString("ButtonCompress", resourceCulture);
            }
        }
        
        internal static string CompressionDone {
            get {
                return ResourceManager.GetString("CompressionDone", resourceCulture);
            }
        }
        
        internal static string CompressionQuality {
            get {
                return ResourceManager.GetString("CompressionQuality", resourceCulture);
            }
        }
        
        internal static string CompressionReady {
            get {
                return ResourceManager.GetString("CompressionReady", resourceCulture);
            }
        }
        
        internal static string CompressionStarted {
            get {
                return ResourceManager.GetString("CompressionStarted", resourceCulture);
            }
        }
        
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        internal static string MenuActions {
            get {
                return ResourceManager.GetString("MenuActions", resourceCulture);
            }
        }
        
        internal static string MenuAddPdf {
            get {
                return ResourceManager.GetString("MenuAddPdf", resourceCulture);
            }
        }
        
        internal static string MenuClearLog {
            get {
                return ResourceManager.GetString("MenuClearLog", resourceCulture);
            }
        }
        
        internal static string MenuCompressPdf {
            get {
                return ResourceManager.GetString("MenuCompressPdf", resourceCulture);
            }
        }
        
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        internal static string MenuExtractImages {
            get {
                return ResourceManager.GetString("MenuExtractImages", resourceCulture);
            }
        }
        
        internal static string MenuExtractText {
            get {
                return ResourceManager.GetString("MenuExtractText", resourceCulture);
            }
        }
        
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        internal static string MenuRemoveAll {
            get {
                return ResourceManager.GetString("MenuRemoveAll", resourceCulture);
            }
        }
        
        internal static string MenuRemovePages {
            get {
                return ResourceManager.GetString("MenuRemovePages", resourceCulture);
            }
        }
        
        internal static string MenuSafeMerge {
            get {
                return ResourceManager.GetString("MenuSafeMerge", resourceCulture);
            }
        }
        
        internal static string MenuSplitPdf {
            get {
                return ResourceManager.GetString("MenuSplitPdf", resourceCulture);
            }
        }
        
        internal static string QualityHigh {
            get {
                return ResourceManager.GetString("QualityHigh", resourceCulture);
            }
        }
        

        internal static string QualityLow {
            get {
                return ResourceManager.GetString("QualityLow", resourceCulture);
            }
        }
        
        internal static string QualityMedium {
            get {
                return ResourceManager.GetString("QualityMedium", resourceCulture);
            }
        }
    }
}